# Generated by Django 4.0.3 on 2022-03-18 09:54

from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_region_options_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[utils.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Регион'),
        ),
    ]
