# Generated by Django 4.0.3 on 2022-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, to='items.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='character',
            field=models.CharField(blank=True, max_length=80, verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='model_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
